category = {
    ".mp4": "Videos",
    ".mkv": "Videos",
    ".avi": "Videos",
    ".mov": "Videos",
    ".flv": "Videos",
    ".mp3": "Audio Files",
    ".wav": "Audio Files",
    ".pdf": "Books",
    ".html": "Books",
    ".doc": "Text Files",
    ".docx": "Text Files",
    ".txt": "Text Files",
    ".py": "Code Files",
    ".c": "Code Files",
    ".csv": "Excel Files",
    ".xlsx": "Excel Files",
    ".exe": "Executable Files",
    ".rar":"Archives",
    ".log":"logs",
    ".pptx":"Presentation Files",
    ".ppsx":"Presentation Files",
    ".potx":"Presentation Files",
    ".json":"Data Files",
    ".xml":"Data Files",
    ".zip":"Archives",
    ".7z":"Archives"
}